### ISSUE TITLE
Routing not working because of wrong URI

### ISSUE THREAD

**Issue by thexpand** [mezzio/mezzio-swoole#59]
#### Summary

I have set up Swoole with Mezzio using the `mezzio/mezzio-swoole` package. I'm running the application with Docker, based on the `phpswoole/swoole:4.6-php7.4-alpine` image. I have set up 2 routes in the `config/routes.php`, one is `/foo` another is `/bar`. However, when I try to open `/foo` or `/bar` in the browser, it matches the `/` route instead, which is non-existent in my case and it falls back to the `NotFoundHandler`.

#### Current behavior

I tried to intercept the request by placing a middleware before the `RouteMiddleware` to see what does the request contain and I tried printing out the `$request->getUri()->getPath()`. Regardless of what URL I use to make the request to, the resulting URI path is always `/`.

#### How to reproduce

1. Setup a mezzio application
2. Add swoole
3. Configure this in a Docker environment with an entrypoint or cmd to run `./vendor/bin/laminas mezzio:swoole:start`
4. Create a route which is not the root, e.g. `/foo` with a `FooHandler`
5. Try to visit the `/foo` URL

#### Expected behavior

The expected behavior would be for the application to match the request to the specified route. For some reason it seems that Swoole/Mezzio does not recognize the URI path and always shows and matches the root `/` instead.

**Comment by weierophinney** [comment]
I cannot recreate the issue.

Here were my steps:

- Started a new Mezzio application: `composer create-project mezzio/mezzio-skeleton mezzio-swoole-59` (I used defaults, except that I chose Plates for my templating.)
- Add "foo" and "bar" handlers:
  ```bash
  $ ./vendor/bin/mezzio handler:create "App\Handler\FooHandler"
  $ ./vendor/bin/mezzio handler:create "App\Handler\BarHandler"
  ```
- I registered these as routes in the `config/routes.php` file:
  ```php
  $app->get('/foo', App\Handler\FooHandler::class, 'foo');
  $app->get('/bar', App\Handler\BarHandler::class, 'bar');
  ```
- I installed mezzio-swoole: `composer require mezzio/mezzio-swoole`
- I configured a mezzio swoole HTTP server, by creating a `config/autoload/swoole.global.php` file with the following contents:
  ```php
  return [
      'mezzio-swoole' => [
          'swoole-http-server' => [
              'host' => '0.0.0.0',
              'port' => 9000,
          ],
      ],
  ];
  ```
- I created an entrypoint script, `bin/entrypoint.sh`, with the following contents, and made it executable:
  ```bash
  #!/bin/sh
  echo "Starting web server"
  exec vendor/bin/laminas mezzio:swoole:start
  ```
- I created a `docker-compose.yml` file with the following contents:
  ```yaml
  version: '3.3'
  
  services:
    php:
      image: phpswoole/swoole:4.6-php8.0
      ports:
        - "9000:9000"
      volumes:
        - .:/var/www
        - ./bin/entrypoint.sh:/usr/local/bin/entrypoint
      working_dir: /var/www
      entrypoint: /usr/local/bin/entrypoint
      logging:
        options:
          max-size: 50m
  ```
- I ran `docker-compose up`
- I then accessed each of the following URLs using HTTPie:
  - localhost:9000/foo
  - localhost:9000/bar
  - localhost:9000/api/ping

Each of these resolved perfectly for me.

I tried the above using each of phpswoole/swoole:4.6-php7.4 and phpswoole/swoole:4.6-php7.4-alpine as the image, and it worked the same in each case.

Is it possible you forgot to add mezzio-swoole configuration?
